#!/usr/bin/env node
// Generate scalar bindings from compiler-validated Cap'n Proto layouts.
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const schema = "runtime-sdk/protocols/system/v1/runtime_binding.capnp";
const schemaDirectory = path.dirname(schema);
const schemas = readdirSync(path.join(root, schemaDirectory)).filter(name => name.endsWith(".capnp")).sort();
execFileSync("capnp", ["compile", "-o-", ...schemas.map(name => `${schemaDirectory}/${name}`)], {
  cwd: root, timeout: 10000, stdio: ["ignore", "ignore", "pipe"],
});
const compiled = execFileSync("capnp", ["compile", "-ocapnp", schema], {
  cwd: root, encoding: "utf8", timeout: 10000, maxBuffer: 1024 * 1024,
});
const structs = [];
for (const match of compiled.matchAll(/struct (\w+) @0x[\da-f]+ \{\s*# (\d+) bytes, (\d+) ptrs\n([\s\S]*?)\n\}/g)) {
  if (Number(match[3]) !== 0) throw new Error("Binding records cannot contain pointers");
  const fields = [...match[4].matchAll(/  (\w+) @(\d+) :(UInt32|UInt64);\s*# bits\[(\d+), (\d+)\)/g)]
    .map((field) => ({ name: field[1], bits: Number(field[3].slice(4)), offset: Number(field[4]) / 8 }));
  if (fields.length !== match[4].split(";").length - 1) throw new Error("Unsupported binding field");
  structs.push({ name: match[1], bytes: Number(match[2]), fields });
}
if (structs.length !== 2) throw new Error("Expected request and receipt contracts");
const upper = (name) => name.replace(/([a-z\d])([A-Z])/g, "$1_$2").toUpperCase();
const pascal = (name) => (name[0].toUpperCase() + name.slice(1)).replace(/Id$/, "ID");
const banner = "// Code generated by runtime-sdk/scripts/generate_binding_contracts.mjs. DO NOT EDIT.\n";
const go = [banner, "package placement\n", 'import ("encoding/binary"; "errors")\n',
  'var errBindingFrame = errors.New("invalid binding Cap’n Proto scalar frame")\n'];
const rust = [banner];
const ts = [banner];
for (const record of structs) {
  const { name, bytes, fields } = record;
  go.push(`const ${name}Bytes = ${bytes + 16}\n`, `type ${name} struct {`);
  rust.push("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]", `pub struct ${name} {`);
  ts.push(`export type ${name} = {`);
  for (const f of fields) {
    go.push(`${pascal(f.name)} uint${f.bits}`);
    rust.push(`pub ${upper(f.name).toLowerCase()}: u${f.bits},`);
    ts.push(`${f.name}: ${f.bits === 64 ? "bigint" : "number"};`);
  }
  go.push("}\n"); rust.push("}\n"); ts.push("};\n");
  go.push(`func (v ${name}) EncodeTo(dst []byte) error {`,
    `if len(dst) != ${name}Bytes { return errBindingFrame }`, "clear(dst)",
    `binary.LittleEndian.PutUint32(dst[4:8], ${bytes / 8 + 1})`,
    `binary.LittleEndian.PutUint64(dst[8:16], uint64(${bytes / 8}) << 32)`);
  for (const f of fields) go.push(`binary.LittleEndian.PutUint${f.bits}(dst[${16 + f.offset}:], v.${pascal(f.name)})`);
  go.push("return nil", "}\n", `func Decode${name}(src []byte) (${name}, error) {`, `var v ${name}`,
    `if len(src) != ${name}Bytes || binary.LittleEndian.Uint32(src[:4]) != 0 ||`,
    `binary.LittleEndian.Uint32(src[4:8]) != ${bytes / 8 + 1} || binary.LittleEndian.Uint64(src[8:16]) != uint64(${bytes / 8}) << 32 { return v, errBindingFrame }`);
  for (const f of fields) go.push(`v.${pascal(f.name)} = binary.LittleEndian.Uint${f.bits}(src[${16 + f.offset}:])`);
  go.push("return v, nil", "}\n");
  rust.push(`impl ${name} {`, `pub const BYTES: usize = ${bytes + 16};`,
    "pub fn encode_to(&self, dst: &mut [u8]) -> Result<(), &'static str> {",
    'if dst.len() != Self::BYTES { return Err("invalid binding frame size"); }', "dst.fill(0);",
    `dst[4..8].copy_from_slice(&${bytes / 8 + 1}u32.to_le_bytes());`,
    `dst[8..16].copy_from_slice(&${BigInt(bytes / 8) << 32n}u64.to_le_bytes());`);
  for (const f of fields) rust.push(`dst[${16 + f.offset}..${16 + f.offset + f.bits / 8}].copy_from_slice(&self.${upper(f.name).toLowerCase()}.to_le_bytes());`);
  rust.push("Ok(())", "}", "pub fn decode(src: &[u8]) -> Result<Self, &'static str> {",
    `if src.len() != Self::BYTES || src[..4] != [0; 4] || src[4..8] != ${bytes / 8 + 1}u32.to_le_bytes() || src[8..16] != ${BigInt(bytes / 8) << 32n}u64.to_le_bytes() { return Err("invalid binding frame layout"); }`,
    "Ok(Self {");
  for (const f of fields) rust.push(`${upper(f.name).toLowerCase()}: u${f.bits}::from_le_bytes(src[${16 + f.offset}..${16 + f.offset + f.bits / 8}].try_into().map_err(|_| "invalid field")?),`);
  rust.push("})", "}", "}\n");
  ts.push(`export const ${name}Bytes = ${bytes + 16};`,
    `export function encode${name}(value: ${name}, bytes: Uint8Array): void {`,
    `if (bytes.byteLength !== ${name}Bytes) throw new Error("Invalid binding frame size");`,
    "const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);", "bytes.fill(0);",
    `view.setUint32(4, ${bytes / 8 + 1}, true);`, `view.setBigUint64(8, ${BigInt(bytes / 8) << 32n}n, true);`);
  for (const f of fields) {
    ts.push(f.bits === 64
      ? `if (value.${f.name} < 0n || value.${f.name} > 0xffffffffffffffffn) throw new Error("Invalid ${f.name}");`
      : `if (!Number.isInteger(value.${f.name}) || value.${f.name} < 0 || value.${f.name} > 0xffffffff) throw new Error("Invalid ${f.name}");`);
    ts.push(`view.${f.bits === 64 ? "setBigUint64" : "setUint32"}(${16 + f.offset}, value.${f.name}, true);`);
  }
  ts.push("}", `export function decode${name}(bytes: Uint8Array): ${name} {`,
    `if (bytes.byteLength !== ${name}Bytes) throw new Error("Invalid binding frame size");`,
    "const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);",
    `if (view.getUint32(0, true) !== 0 || view.getUint32(4, true) !== ${bytes / 8 + 1} || view.getBigUint64(8, true) !== ${BigInt(bytes / 8) << 32n}n) throw new Error("Invalid binding frame layout");`, "return {");
  for (const f of fields) ts.push(`${f.name}: view.${f.bits === 64 ? "getBigUint64" : "getUint32"}(${16 + f.offset}, true),`);
  ts.push("};", "}\n");
}
const outputs = new Map([
  ["server-kit/go/placement/binding_contract_gen.go", execFileSync("gofmt", [], { input: go.join("\n"), encoding: "utf8", timeout: 10000 })],
  ["runtime-sdk/rust/crates/ovrt-core/src/binding_contract_gen.rs", execFileSync("rustfmt", ["--edition", "2021", "--emit", "stdout"], { input: rust.join("\n"), encoding: "utf8", timeout: 10000 })],
  ["runtime-sdk/ts/browser-host/src/generated/bindingContracts.ts", ts.join("\n")],
]);
for (const [file, content] of outputs) {
  const target = path.join(root, file);
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== content) throw new Error(`Stale generated binding: ${file}`);
  } else writeFileSync(target, content);
}
console.log("Binding contracts match compiler layouts");
