#!/bin/zsh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA_DIR="$ROOT_DIR/protocols/system/v1"
RUST_OUT="$ROOT_DIR/rust/crates/ovrt-core/src/generated.rs"
TS_OUT="$ROOT_DIR/ts/browser-host/src/generated/runtimeBuffer.ts"
GO_OUT="$ROOT_DIR/go/runtimehost/generated/runtime_buffer_gen.go"

if [[ ! -d "$SCHEMA_DIR" ]]; then
  echo "missing runtime schema directory: $SCHEMA_DIR" >&2
  exit 1
fi

schema_paths=("$SCHEMA_DIR"/*.capnp)
if [[ "${#schema_paths[@]}" -eq 0 || ! -f "${schema_paths[1]}" ]]; then
  echo "missing runtime schemas in: $SCHEMA_DIR" >&2
  exit 1
fi

{
  cat <<'EOF'
// Code generated by runtime-sdk/scripts/generate_system_bindings.sh. DO NOT EDIT.

EOF
  awk '
    function export_name(name, out, i, ch) {
      if (name ~ /^[A-Z0-9_]+$/) return name
      out=""
      for (i=1; i<=length(name); i++) {
        ch=substr(name, i, 1)
        if (ch ~ /[A-Z]/ && i > 1) out=out "_"
        out=out toupper(ch)
      }
      gsub(/__+/, "_", out)
      return out
    }
    /^const / {
      value=$5
      gsub(/;/, "", value)
      printf "pub const %s: u32 = %s;\n", export_name($2), value
    }
  ' "${schema_paths[@]}"
} > "$RUST_OUT"

{
  cat <<'EOF'
// Code generated by runtime-sdk/scripts/generate_system_bindings.sh. DO NOT EDIT.

EOF
  awk '
    function export_name(name, out, i, ch) {
      if (name ~ /^[A-Z0-9_]+$/) return name
      out=""
      for (i=1; i<=length(name); i++) {
        ch=substr(name, i, 1)
        if (ch ~ /[A-Z]/ && i > 1) out=out "_"
        out=out toupper(ch)
      }
      gsub(/__+/, "_", out)
      return out
    }
    /^const / {
      value=$5
      gsub(/;/, "", value)
      printf "export const %s = %s;\n", export_name($2), value
    }
  ' "${schema_paths[@]}"
} > "$TS_OUT"

{
  cat <<'EOF'
// Code generated by runtime-sdk/scripts/generate_system_bindings.sh. DO NOT EDIT.

package generated

EOF
  awk '
    function export_name(name, out, i, ch) {
      if (name ~ /^[A-Z0-9_]+$/) return name
      out=""
      for (i=1; i<=length(name); i++) {
        ch=substr(name, i, 1)
        if (ch ~ /[A-Z]/ && i > 1) out=out "_"
        out=out toupper(ch)
      }
      gsub(/__+/, "_", out)
      return out
    }
    /^const / {
      value=$5
      gsub(/;/, "", value)
      printf "const %s uint32 = %s\n", export_name($2), value
    }
  ' "${schema_paths[@]}"
} > "$GO_OUT"

echo "generated runtime system bindings"
