#!/bin/zsh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA_PATH="$ROOT_DIR/protocols/system/v1/runtime_buffer.capnp"
RUST_OUT="$ROOT_DIR/rust/crates/ovrt-core/src/generated.rs"
TS_OUT="$ROOT_DIR/ts/browser-host/src/generated/runtimeBuffer.ts"
GO_OUT="$ROOT_DIR/go/runtimehost/generated/runtime_buffer_gen.go"

if [[ ! -f "$SCHEMA_PATH" ]]; then
  echo "missing runtime schema: $SCHEMA_PATH" >&2
  exit 1
fi

{
  cat <<'EOF'
// Code generated by runtime-sdk/scripts/generate_system_bindings.sh. DO NOT EDIT.

EOF
  awk '
    /^const / {
      value=$5
      gsub(/;/, "", value)
      printf "pub const %s: u32 = %s;\n", $2, value
    }
  ' "$SCHEMA_PATH"
} > "$RUST_OUT"

{
  cat <<'EOF'
// Code generated by runtime-sdk/scripts/generate_system_bindings.sh. DO NOT EDIT.

EOF
  awk '
    /^const / {
      value=$5
      gsub(/;/, "", value)
      printf "export const %s = %s;\n", $2, value
    }
  ' "$SCHEMA_PATH"
} > "$TS_OUT"

{
  cat <<'EOF'
// Code generated by runtime-sdk/scripts/generate_system_bindings.sh. DO NOT EDIT.

package generated

EOF
  awk '
    /^const / {
      value=$5
      gsub(/;/, "", value)
      printf "const %s uint32 = %s\n", $2, value
    }
  ' "$SCHEMA_PATH"
} > "$GO_OUT"

echo "generated runtime system bindings"
