#!/usr/bin/env node
/**
 * generate_frontend_commands.mjs
 *
 * Transforms the backend-authoritative route catalog into the per-app frontend
 * route registry consumed by `@ovasabi/runtime-transport` (createCommandBus /
 * createRouteRegistry).
 *
 * Source of truth: route_catalog.json, emitted by the app's Go route-catalog
 * command via `httpapi.MarshalRouteCatalog([]registry.HTTPRoute)`. Because the
 * catalog comes from the routes the server actually registers, this generator
 * never re-derives method/capability/permission (which would drift from
 * server-kit's catalog.go) and it automatically includes hand-registered,
 * non-event routes such as the transfer/upload routes.
 *
 * Output: a generated `RuntimeRoute[]` plus a typed `createAppRouteRegistry()`
 * helper and an `AppEventType` union. The app wires the registry into the
 * command bus itself (matching the "generate data, app wires the bus" split).
 *
 * Usage:
 *   node tooling/scripts/generate_frontend_commands.mjs [options]
 *
 * Options:
 *   --catalog <file>   Route catalog JSON. Default: docs/references/lifecycle/route_catalog.json
 *   --out <file>       Generated TypeScript. Default: frontend/src/generated/runtimeRoutes.ts
 *   --package <name>   runtime-transport import specifier. Default: @ovasabi/runtime-transport
 *   --check            Fail if the output is missing or stale (CI mode).
 *   --help             Print this message.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const SUPPORTED_SCHEMA = "1.0";
const DEFAULT_CATALOG = "docs/references/lifecycle/route_catalog.json";
const DEFAULT_OUT = "frontend/src/generated/runtimeRoutes.ts";
const DEFAULT_PACKAGE = "@ovasabi/runtime-transport";

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    printHelp();
    return;
  }
  const catalogPath = path.resolve(args.catalog ?? DEFAULT_CATALOG);
  const outPath = path.resolve(args.out ?? DEFAULT_OUT);
  const pkg = args.package ?? DEFAULT_PACKAGE;

  if (!existsSync(catalogPath)) {
    // No catalog yet (e.g. Foundation core, or an app before its first route
    // emit). Mirror the prototype generator: it is only a failure in --check
    // mode when an output already exists and would now be stale/orphaned.
    if (args.check && existsSync(outPath)) {
      fail(`route catalog missing but generated output exists: ${rel(outPath)}\n  run the app route-catalog command, then: make generate-contracts`);
    }
    console.log(`[SKIP] route catalog not found: ${rel(catalogPath)}`);
    return;
  }

  const catalog = loadCatalog(catalogPath);
  const content = render(catalog, pkg, rel(catalogPath));

  if (args.check) {
    if (!existsSync(outPath)) {
      fail(`frontend route registry missing: ${rel(outPath)}\n  run: make generate-contracts`);
    }
    if (readFileSync(outPath, "utf8") !== content) {
      fail(`frontend route registry is stale: ${rel(outPath)}\n  run: make generate-contracts`);
    }
    console.log(`[OK] frontend route registry current: ${rel(outPath)}`);
    return;
  }

  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, content);
  console.log(`[OK] generated ${catalog.routes.length} routes at ${rel(outPath)}`);
}

function loadCatalog(catalogPath) {
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(catalogPath, "utf8"));
  } catch (error) {
    fail(`route catalog is not valid JSON: ${rel(catalogPath)}\n  ${error.message}`);
  }
  if (parsed.schema_version !== SUPPORTED_SCHEMA) {
    fail(`route catalog schema ${parsed.schema_version} is unsupported (want ${SUPPORTED_SCHEMA})`);
  }
  const routes = Array.isArray(parsed.routes) ? parsed.routes : [];
  for (const route of routes) {
    validateRoute(route, catalogPath);
  }
  return { schemaVersion: parsed.schema_version, routes };
}

const PERMISSIONS = new Set(["view", "write", "admin"]);

function validateRoute(route, catalogPath) {
  for (const field of ["method", "path", "event_type", "permission"]) {
    if (typeof route[field] !== "string" || route[field].trim() === "") {
      fail(`route in ${rel(catalogPath)} is missing "${field}": ${JSON.stringify(route)}`);
    }
  }
  if (!PERMISSIONS.has(route.permission)) {
    fail(`route ${route.event_type} has invalid permission "${route.permission}" (want view|write|admin)`);
  }
}

function render(catalog, pkg, sourceLabel) {
  const lines = [];
  lines.push("// Code generated by generate_frontend_commands.mjs. DO NOT EDIT.");
  lines.push(`// Source: ${sourceLabel} (schema ${catalog.schemaVersion})`);
  lines.push("");
  lines.push(`import { createRouteRegistry, type RouteRegistry, type RuntimeRoute } from "${pkg}";`);
  lines.push("");

  if (catalog.routes.length === 0) {
    lines.push("export const runtimeRoutes: readonly RuntimeRoute[] = [] as const;");
    lines.push("");
    lines.push("export type AppEventType = never;");
  } else {
    lines.push("export const runtimeRoutes: readonly RuntimeRoute[] = [");
    for (const route of catalog.routes) {
      lines.push(`  ${renderRoute(route)},`);
    }
    lines.push("] as const;");
    lines.push("");
    lines.push("export type AppEventType =");
    const eventTypes = uniqueSorted(catalog.routes.map((route) => route.event_type));
    eventTypes.forEach((eventType, index) => {
      const suffix = index === eventTypes.length - 1 ? ";" : "";
      lines.push(`  | ${JSON.stringify(eventType)}${suffix}`);
    });
  }

  lines.push("");
  lines.push("export const createAppRouteRegistry = (): RouteRegistry =>");
  lines.push("  createRouteRegistry(runtimeRoutes as RuntimeRoute[]);");
  lines.push("");
  return lines.join("\n");
}

function renderRoute(route) {
  const fields = [
    `method: ${JSON.stringify(route.method)}`,
    `path: ${JSON.stringify(route.path)}`,
    `eventType: ${JSON.stringify(route.event_type)}`,
    `requiredCapability: ${JSON.stringify(route.required_capability ?? "")}`,
    `permission: ${JSON.stringify(route.permission)}`,
  ];
  return `{ ${fields.join(", ")} }`;
}

function uniqueSorted(values) {
  return Array.from(new Set(values)).sort();
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case "--catalog":
        args.catalog = requireValue(argv, ++index, arg);
        break;
      case "--out":
        args.out = requireValue(argv, ++index, arg);
        break;
      case "--package":
        args.package = requireValue(argv, ++index, arg);
        break;
      case "--check":
        args.check = true;
        break;
      case "--help":
      case "-h":
        args.help = true;
        break;
      default:
        fail(`unknown option: ${arg}`);
    }
  }
  return args;
}

function requireValue(argv, index, flag) {
  const value = argv[index];
  if (value === undefined || value.startsWith("--")) {
    fail(`${flag} requires a value`);
  }
  return value;
}

function rel(target) {
  return path.relative(process.cwd(), target) || path.basename(target);
}

function fail(message) {
  console.error(`[FAIL] ${message}`);
  process.exit(1);
}

function printHelp() {
  const text = readFileSync(new URL(import.meta.url), "utf8");
  const banner = text.slice(text.indexOf("/**"), text.indexOf("*/") + 2);
  console.log(banner.replace(/^\/\*\*?|\*\/$/g, "").replace(/^ \* ?/gm, ""));
}

main();
