#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

function main() {
  const args = parseArgs(process.argv.slice(2));
  const schemaRoot = path.resolve(args.schemaRoot ?? "runtime-sdk/protocols/system/v1");
  const outPath = path.resolve(args.out ?? "runtime-sdk/ts/browser-host/src/generated/runtimeContracts.ts");

  const manifest = discoverRuntimeContracts(schemaRoot);
  const content = renderTypescriptManifest(manifest, stableLabel(schemaRoot));

  if (args.check) {
    if (!existsSync(outPath)) {
      console.error(`[FAIL] runtime contract manifest missing: ${relativeToCwd(outPath)}`);
      console.error("  run: make generate-contracts");
      process.exit(1);
    }
    const current = readFileSync(outPath, "utf8");
    if (current !== content) {
      console.error(`[FAIL] runtime contract manifest is stale: ${relativeToCwd(outPath)}`);
      console.error("  run: make generate-contracts");
      process.exit(1);
    }
    console.log(`[OK] runtime contract manifest current: ${relativeToCwd(outPath)}`);
    return;
  }

  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, content);
  console.log(`[OK] generated runtime contract manifest at ${relativeToCwd(outPath)}`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case "--schema-root":
        args.schemaRoot = requireValue(argv, ++index, arg);
        break;
      case "--out":
        args.out = requireValue(argv, ++index, arg);
        break;
      case "--check":
        args.check = true;
        break;
      case "--help":
      case "-h":
        printHelp();
        process.exit(0);
        break;
      default:
        throw new Error(`unknown argument: ${arg}`);
    }
  }
  return args;
}

function requireValue(argv, index, flag) {
  const value = argv[index];
  if (!value || value.startsWith("--")) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
}

function printHelp() {
  console.log(`Usage: node tooling/scripts/generate_runtime_contract_manifest.mjs [options]

Options:
  --schema-root <dir>  Cap'n Proto schema directory. Defaults to runtime-sdk/protocols/system/v1.
  --out <file>         Generated TypeScript manifest. Defaults to runtime-sdk/ts/browser-host/src/generated/runtimeContracts.ts.
  --check              Fail when generated output is missing or stale.
`);
}

function discoverRuntimeContracts(schemaRoot) {
  if (!existsSync(schemaRoot) || !statSync(schemaRoot).isDirectory()) {
    throw new Error(`runtime contract schema root missing: ${schemaRoot}`);
  }

  return findCapnpFiles(schemaRoot).map((filePath) => {
    const text = readFileSync(filePath, "utf8");
    const relativePath = path.relative(schemaRoot, filePath).split(path.sep).join("/");
    return {
      file: relativePath,
      id: matchOne(text, /^\s*@([^;]+);/m) ?? "",
      constants: parseConstants(text),
      structs: parseNamedBlocks(text, "struct"),
      enums: parseNamedBlocks(text, "enum"),
    };
  });
}

function findCapnpFiles(root) {
  return readdirSync(root)
    .filter((entry) => entry.endsWith(".capnp"))
    .sort()
    .map((entry) => path.join(root, entry));
}

function parseConstants(text) {
  const constants = [];
  const pattern = /^\s*const\s+([A-Za-z0-9_]+)\s+:([A-Za-z0-9_]+)\s+=\s+([^;]+);/gm;
  let match;
  while ((match = pattern.exec(text)) !== null) {
    constants.push({
      name: match[1],
      type: match[2],
      value: match[3].trim(),
    });
  }
  return constants;
}

function parseNamedBlocks(text, keyword) {
  const names = [];
  const pattern = new RegExp(`^\\s*${keyword}\\s+([A-Za-z0-9_]+)\\s*[{]`, "gm");
  let match;
  while ((match = pattern.exec(text)) !== null) {
    names.push(match[1]);
  }
  return names;
}

function matchOne(text, pattern) {
  const match = pattern.exec(text);
  return match?.[1] ?? null;
}

function renderTypescriptManifest(manifest, schemaRootLabel) {
  return `// Code generated by tooling/scripts/generate_runtime_contract_manifest.mjs. DO NOT EDIT.

export type RuntimeContractConstant = {
  readonly name: string;
  readonly type: string;
  readonly value: string;
};

export type RuntimeContractFile = {
  readonly file: string;
  readonly id: string;
  readonly constants: readonly RuntimeContractConstant[];
  readonly structs: readonly string[];
  readonly enums: readonly string[];
};

export const runtimeContractManifest = ${JSON.stringify({
    schemaRoot: schemaRootLabel,
    files: manifest,
  }, null, 2)} as const satisfies {
  readonly schemaRoot: string;
  readonly files: readonly RuntimeContractFile[];
};
`;
}

function stableLabel(schemaRoot) {
  const normalized = schemaRoot.split(path.sep).join("/");
  if (normalized.endsWith("/runtime-sdk/protocols/system/v1")) {
    return "runtime-sdk/protocols/system/v1";
  }
  if (normalized.endsWith("/foundation/runtime-sdk/protocols/system/v1")) {
    return "runtime-sdk/protocols/system/v1";
  }
  const relative = path.relative(process.cwd(), schemaRoot);
  return (relative || schemaRoot).split(path.sep).join("/");
}

function relativeToCwd(filePath) {
  return (path.relative(process.cwd(), filePath) || ".").split(path.sep).join("/");
}

main();
