#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

const __filename = fileURLToPath(import.meta.url);
const foundationDir = path.resolve(path.dirname(__filename), "../..");
let FieldDescriptorProto_Label;
let FieldDescriptorProto_Type;
let FileDescriptorSet;

const GENERATED_HEADER = `// Generated by foundation/tooling/scripts/generate_frontend_prototype_runtime.mjs.
// Do not edit by hand.
`;

const REQUEST_RESPONSE_SUFFIX = /(Request|Response|Metadata|Envelope|Command|Event|Descriptor|Error)$/;
const ENTITY_SUFFIX = /(Entity|Record|View|Item|State|Snapshot|Model)$/;
const SENSITIVE_ID_FIELDS = new Set([
  "organization_id",
  "tenant_id",
  "owner_id",
  "user_id",
  "role_id",
  "permission_id",
]);

function main() {
  const args = parseArgs(process.argv.slice(2));
  const protoRootArg = args.protoRoot ?? "api/protos";
  const protoRoot = path.resolve(protoRootArg);
  const outPath = path.resolve(args.out ?? "frontend/src/generated/prototypeRuntime.ts");
  const includeTemplate = Boolean(args.includeTemplate);
  const packageImport = args.packageImport ?? "@ovasabi/frontend-kit";
  const protoRootLabel = stableProtoRootLabel(protoRootArg, protoRoot);

  const discovery = discoverPrototypeSchemas(protoRoot, includeTemplate);
  if (discovery.errors.length > 0) {
    for (const error of discovery.errors) {
      console.error(`[frontend-prototype-runtime] ${error}`);
    }
    process.exit(1);
  }

  const content = renderTypeScript({
    packageImport,
    protoRootLabel,
    schemas: discovery.schemas,
  });

  if (args.check) {
    if (discovery.schemas.length === 0 && !existsSync(outPath)) {
      console.log("[OK] no frontend prototype schemas discovered");
      return;
    }
    if (!existsSync(outPath)) {
      console.error(`[FAIL] frontend prototype runtime output missing: ${relativeToCwd(outPath)}`);
      console.error("  run: node tooling/scripts/generate_frontend_prototype_runtime.mjs");
      process.exit(1);
    }
    const current = readFileSync(outPath, "utf8");
    if (current !== content) {
      console.error(`[FAIL] frontend prototype runtime output is stale: ${relativeToCwd(outPath)}`);
      console.error("  run: node tooling/scripts/generate_frontend_prototype_runtime.mjs");
      process.exit(1);
    }
    console.log(`[OK] frontend prototype runtime current: ${relativeToCwd(outPath)}`);
    return;
  }

  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, content);
  console.log(`[OK] generated ${discovery.schemas.length} frontend prototype schemas at ${relativeToCwd(outPath)}`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case "--proto-root":
        args.protoRoot = requireValue(argv, ++index, arg);
        break;
      case "--out":
        args.out = requireValue(argv, ++index, arg);
        break;
      case "--package-import":
        args.packageImport = requireValue(argv, ++index, arg);
        break;
      case "--include-template":
        args.includeTemplate = true;
        break;
      case "--check":
        args.check = true;
        break;
      case "--help":
      case "-h":
        printHelp();
        process.exit(0);
        break;
      default:
        throw new Error(`unknown argument: ${arg}`);
    }
  }
  return args;
}

function requireValue(argv, index, flag) {
  const value = argv[index];
  if (!value || value.startsWith("--")) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
}

function printHelp() {
  console.log(`Usage: node generate_frontend_prototype_runtime.mjs [options]

Options:
  --proto-root <dir>       App protobuf root. Defaults to api/protos.
  --out <file>             Generated TypeScript path. Defaults to frontend/src/generated/prototypeRuntime.ts.
  --package-import <name>  Runtime workbench import. Defaults to @ovasabi/frontend-kit.
  --include-template       Include api/protos/_template fixtures.
  --check                  Fail when the generated output is missing or stale.
`);
}

function discoverPrototypeSchemas(protoRoot, includeTemplate) {
  const errors = [];
  const schemas = [];
  if (!existsSync(protoRoot)) {
    return { schemas, errors };
  }

  const protoFiles = findProtoFiles(protoRoot).filter((file) => {
    const normalized = path.relative(protoRoot, file).split(path.sep).join("/");
    const isTemplateProto =
      normalized === "_template" ||
      normalized.startsWith("_template/") ||
      normalized.includes("/_template/");
    if (!includeTemplate && isTemplateProto) {
      return false;
    }
    return !/^(common|foundation|google|hermes|runtime|system|transport)\//.test(normalized);
  });
  if (protoFiles.length === 0) {
    return { schemas, errors };
  }

  if (!loadDescriptorModule(errors)) {
    return { schemas, errors };
  }

  const descriptorSet = readDescriptorSet(protoRoot, protoFiles, errors);
  if (!descriptorSet) return { schemas, errors };

  const index = buildDescriptorIndex(descriptorSet);
  for (const file of descriptorSet.file) {
    if (!isDomainSource(file, includeTemplate)) continue;
    for (const message of file.messageType) {
      const schema = schemaFromMessage(file, message, index);
      if (schema) schemas.push(schema);
    }
  }

  schemas.sort((left, right) => left.key.localeCompare(right.key));
  return { schemas, errors };
}

function loadDescriptorModule(errors) {
  if (FileDescriptorSet) return true;
  const candidates = [
    path.join(foundationDir, "runtime-transport/ts/package.json"),
    path.resolve("foundation/runtime-transport/ts/package.json"),
    path.resolve("runtime-transport/ts/package.json"),
    path.resolve("frontend/package.json"),
    path.resolve("package.json"),
  ];
  const seen = new Set();

  for (const candidate of candidates) {
    if (seen.has(candidate) || !existsSync(candidate)) continue;
    seen.add(candidate);
    try {
      const descriptorModule = createRequire(candidate)("ts-proto-descriptors");
      FieldDescriptorProto_Label = descriptorModule.FieldDescriptorProto_Label;
      FieldDescriptorProto_Type = descriptorModule.FieldDescriptorProto_Type;
      FileDescriptorSet = descriptorModule.FileDescriptorSet;
      return true;
    } catch {
      // Keep searching known generated-app and Foundation package roots.
    }
  }

  errors.push(
    "ts-proto-descriptors is required; run npm install in foundation/runtime-transport/ts or the generated app frontend"
  );
  return false;
}

function findProtoFiles(root) {
  const files = [];
  walk(root, files);
  return files.sort();
}

function walk(dir, files) {
  for (const entry of readdirSync(dir).sort()) {
    const fullPath = path.join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      walk(fullPath, files);
      continue;
    }
    if (entry.endsWith(".proto")) {
      files.push(fullPath);
    }
  }
}

function readDescriptorSet(protoRoot, protoFiles, errors) {
  const descriptorDir = mkdtempSync(path.join(tmpdir(), "ovasabi-prototype-descriptors-"));
  const descriptorPath = path.join(descriptorDir, "schema.pb");
  const relativeFiles = protoFiles.map((file) => path.relative(protoRoot, file).split(path.sep).join("/"));
  const result = spawnSync(
    "protoc",
    [
      `--proto_path=${protoRoot}`,
      `--descriptor_set_out=${descriptorPath}`,
      "--include_imports",
      ...relativeFiles,
    ],
    {
      cwd: protoRoot,
      encoding: "utf8",
    }
  );

  if (result.status !== 0) {
    errors.push(`protoc descriptor generation failed: ${result.stderr || result.stdout || result.error?.message}`);
    rmSync(descriptorDir, { force: true, recursive: true });
    return undefined;
  }

  try {
    return FileDescriptorSet.decode(readFileSync(descriptorPath));
  } finally {
    rmSync(descriptorDir, { force: true, recursive: true });
  }
}

function buildDescriptorIndex(descriptorSet) {
  const messages = new Map();
  const enums = new Map();

  for (const file of descriptorSet.file) {
    for (const message of file.messageType) {
      indexMessage(file.package, "", message, messages, enums);
    }
    for (const enumDescriptor of file.enumType) {
      enums.set(fullName(file.package, "", enumDescriptor.name), enumDescriptor);
    }
  }

  return { enums, messages };
}

function indexMessage(packageName, parent, message, messages, enums) {
  const qualified = fullName(packageName, parent, message.name);
  messages.set(qualified, message);
  for (const enumDescriptor of message.enumType) {
    enums.set(fullName(packageName, parent ? `${parent}.${message.name}` : message.name, enumDescriptor.name), enumDescriptor);
  }
  for (const nested of message.nestedType) {
    indexMessage(packageName, parent ? `${parent}.${message.name}` : message.name, nested, messages, enums);
  }
}

function fullName(packageName, parent, name) {
  const pieces = [packageName, parent, name].filter(Boolean).join(".");
  return `.${pieces}`;
}

function isDomainSource(file, includeTemplate) {
  const name = file.name ?? "";
  const packageName = file.package ?? "";
  if (!includeTemplate && name.includes("/_template/")) return false;
  if (name.startsWith("google/")) return false;
  if (name.startsWith("common/")) return false;
  if (/^(google|common|foundation|system|runtime|transport|hermes)(\.|$)/.test(packageName)) return false;
  return true;
}

function schemaFromMessage(file, message, index) {
  if (!message || message.options?.mapEntry) return undefined;
  if (!message.field || message.field.length === 0) return undefined;
  if (REQUEST_RESPONSE_SUFFIX.test(message.name)) return undefined;

  const idField = chooseIdField(message);
  if (!ENTITY_SUFFIX.test(message.name) && !idField) return undefined;

  const domainInfo = domainFromPackage(file.package, file.name);
  const baseName = stripEntitySuffix(message.name);
  const collection = pluralizeSnake(toSnakeCase(baseName));
  const fields = message.field
    .filter((field) => field.name)
    .map((field) => fieldSpecFromDescriptor(field, index))
    .sort((left, right) => left.name.localeCompare(right.name));

  if (fields.length === 0) return undefined;

  const key = `${domainInfo.domain}.${collection}`;
  return {
    collection,
    domain: domainInfo.domain,
    fields,
    idField: idField ?? "id",
    key,
    messageName: message.name,
    protoFile: file.name,
    typeName: `${domainInfo.domain}_${message.name}`,
    version: domainInfo.version,
  };
}

function chooseIdField(message) {
  const fields = message.field ?? [];
  const direct = fields.find((field) => field.name === "id");
  if (direct) return direct.name;
  const snakeName = toSnakeCase(stripEntitySuffix(message.name));
  const preferred = fields.find((field) => field.name === `${snakeName}_id`);
  if (preferred) return preferred.name;
  const fallback = fields.find((field) => field.name.endsWith("_id") && !SENSITIVE_ID_FIELDS.has(field.name));
  return fallback?.name;
}

function domainFromPackage(packageName, fileName) {
  const parts = (packageName || "").split(".").filter(Boolean);
  const versionIndex = parts.findIndex((part) => /^v\d/.test(part));
  if (versionIndex > 0) {
    return {
      domain: parts.slice(0, versionIndex).join("_"),
      version: parts[versionIndex],
    };
  }

  const fileParts = (fileName || "").split("/");
  const fallbackVersionIndex = fileParts.findIndex((part) => /^v\d/.test(part));
  if (fallbackVersionIndex > 0) {
    return {
      domain: fileParts[fallbackVersionIndex - 1],
      version: fileParts[fallbackVersionIndex],
    };
  }

  return {
    domain: parts[0] || fileParts[0] || "app",
    version: "v1",
  };
}

function fieldSpecFromDescriptor(field, index) {
  const mapField = isMapField(field, index);
  const spec = {
    kind: fieldKind(field, index, mapField),
    name: field.name,
  };
  if (!mapField && field.label === FieldDescriptorProto_Label.LABEL_REPEATED) {
    spec.repeated = true;
  }
  if (!spec.repeated && fieldIsOptional(field)) {
    spec.optional = true;
  }
  const enumValues = enumValuesForField(field, index);
  if (enumValues.length > 0) {
    spec.enumValues = enumValues;
  }
  return spec;
}

function fieldKind(field, index, mapField) {
  const name = field.name.toLowerCase();
  const typeName = normalizeTypeName(field.typeName);
  if (mapField) return "object";
  if (typeName === ".google.protobuf.Timestamp" || /(^|_)(date|time)$/.test(name) || name.endsWith("_at")) {
    return "timestamp";
  }

  switch (field.type) {
    case FieldDescriptorProto_Type.TYPE_BOOL:
      return "bool";
    case FieldDescriptorProto_Type.TYPE_BYTES:
      return "bytes";
    case FieldDescriptorProto_Type.TYPE_DOUBLE:
    case FieldDescriptorProto_Type.TYPE_FLOAT:
      return "float";
    case FieldDescriptorProto_Type.TYPE_ENUM:
      return "enum";
    case FieldDescriptorProto_Type.TYPE_FIXED32:
    case FieldDescriptorProto_Type.TYPE_FIXED64:
    case FieldDescriptorProto_Type.TYPE_INT32:
    case FieldDescriptorProto_Type.TYPE_INT64:
    case FieldDescriptorProto_Type.TYPE_SFIXED32:
    case FieldDescriptorProto_Type.TYPE_SFIXED64:
    case FieldDescriptorProto_Type.TYPE_SINT32:
    case FieldDescriptorProto_Type.TYPE_SINT64:
    case FieldDescriptorProto_Type.TYPE_UINT32:
    case FieldDescriptorProto_Type.TYPE_UINT64:
      return "int";
    case FieldDescriptorProto_Type.TYPE_MESSAGE:
    case FieldDescriptorProto_Type.TYPE_GROUP:
      return "object";
    case FieldDescriptorProto_Type.TYPE_STRING:
    default:
      if (name === "id" || name.endsWith("_id")) return "uuid";
      if (name.includes("email")) return "email";
      if (name.includes("url") || name.includes("uri") || name.includes("link")) return "url";
      if (/(description|summary|content|body|message|notes|bio)/.test(name)) return "text";
      return "string";
  }
}

function fieldIsOptional(field) {
  if (field.proto3Optional) return true;
  if (field.type === FieldDescriptorProto_Type.TYPE_MESSAGE && field.label !== FieldDescriptorProto_Label.LABEL_REPEATED) {
    return true;
  }
  return false;
}

function enumValuesForField(field, index) {
  if (field.type !== FieldDescriptorProto_Type.TYPE_ENUM) return [];
  const enumDescriptor = index.enums.get(normalizeTypeName(field.typeName));
  if (!enumDescriptor) return [];
  return enumDescriptor.value
    .map((value) => value.name)
    .filter((name) => name && !name.endsWith("_UNSPECIFIED") && name !== "UNRECOGNIZED");
}

function isMapField(field, index) {
  if (field.type !== FieldDescriptorProto_Type.TYPE_MESSAGE) return false;
  if (field.label !== FieldDescriptorProto_Label.LABEL_REPEATED) return false;
  const message = index.messages.get(normalizeTypeName(field.typeName));
  return Boolean(message?.options?.mapEntry);
}

function normalizeTypeName(typeName) {
  if (!typeName) return "";
  return typeName.startsWith(".") ? typeName : `.${typeName}`;
}

function renderTypeScript({ packageImport, protoRootLabel, schemas }) {
  const schemaRuntimeImports =
    schemas.length > 0
      ? `  createDummyDataFactory,
  createLiveProjectionBinding,
  createTenantProjectionStore,
`
      : "";
  const sections = [
    GENERATED_HEADER,
    `import {
${schemaRuntimeImports}  createGeneratedHookRegistry,
  createPrototypeRuntimeCache,
  createRuntimeWorkbench,
  type DummyDataFactoryOptions,
  type DummySchemaSpec,
  type LiveProjectionBinding,
  type LiveProjectionBindingOptions,
  type PrototypeMode,
  type PrototypeRuntimeCache,
  type RuntimeWorkbenchAdapter,
  type TenantProjectionStore,
} from ${JSON.stringify(packageImport)};
`,
    `export type PrototypeGeneratedStore = {
  useSnapshot(): unknown;
};

export type PrototypeFixtureState<TRecord extends Record<string, unknown>> = {
  name: string;
  tenantId: string;
  domain: string;
  collection: string;
  records: readonly TRecord[];
};

export type PrototypeBenchmarkFixture = {
  name: string;
  lane: "dummy" | "store";
  records: number;
  run(): unknown;
};

export type PrototypeSchemaRuntimeConstants = {
  key: string;
  domain: string;
  collection: string;
  idField: string;
};

export type PrototypeDomainRuntime = {
  constants: PrototypeSchemaRuntimeConstants;
  schema: DummySchemaSpec;
  createDummyRecords(
    tenantId: string,
    count?: number,
    options?: DummyDataFactoryOptions,
    cache?: PrototypeRuntimeCache
  ): readonly Record<string, unknown>[];
  createStore(
    tenantId: string,
    initialRecords?: readonly Record<string, unknown>[],
    cache?: PrototypeRuntimeCache
  ): TenantProjectionStore<Record<string, unknown>>;
  connectLiveProjection(
    options: Omit<LiveProjectionBindingOptions<Record<string, unknown>>, "scope" | "store"> & {
      tenantId: string;
      store?: TenantProjectionStore<Record<string, unknown>>;
      cache?: PrototypeRuntimeCache;
    }
  ): LiveProjectionBinding<Record<string, unknown>>;
  registerStore(
    tenantId: string,
    store?: TenantProjectionStore<Record<string, unknown>>
  ): TenantProjectionStore<Record<string, unknown>>;
  fixtureStates: Record<string, unknown>;
  benchmarkFixtures: readonly PrototypeBenchmarkFixture[];
};

export const prototypeStoreRegistry = createGeneratedHookRegistry<PrototypeGeneratedStore>();
export const prototypeRuntimeCache = createPrototypeRuntimeCache();

export const createPrototypeRuntimeWorkbench = (
  mode: PrototypeMode = "dummy",
  adapter?: RuntimeWorkbenchAdapter
) => createRuntimeWorkbench(mode, adapter);
`,
  ];

  for (const schema of schemas) {
    sections.push(renderSchema(schema));
  }

  sections.push(renderRegistry({ protoRootLabel, schemas }));
  return `${sections.join("\n")}\n`;
}

function renderSchema(schema) {
  const base = safePascalIdentifier(schema.messageName);
  const variableBase = lowerFirst(base);
  const typeName = `${base}Prototype`;
  const storeName = `${base}Store`;
  const schemaName = `${variableBase}Schema`;
  const constantsName = `${variableBase}RuntimeConstants`;
  const fixtureName = `${variableBase}Fixtures`;
  const stateName = `${variableBase}FixtureStates`;
  const benchmarkName = `${variableBase}BenchmarkFixtures`;
  const factoryName = `create${base}DummyFactory`;
  const cachedDummyName = `createCached${base}DummyRecords`;
  const storeFactoryName = `create${base}Store`;
  const liveBindingName = `connect${base}LiveProjection`;
  const registerName = `register${base}Store`;
  const hookName = `use${base}Snapshot`;

  return `export type ${typeName} = Record<string, unknown>;

export type ${storeName} = TenantProjectionStore<${typeName}>;

export const ${schemaName} = ${stableJson({
    collection: schema.collection,
    domain: schema.domain,
    fields: schema.fields,
    idField: schema.idField,
  })} as const satisfies DummySchemaSpec;

export const ${factoryName} = (options: DummyDataFactoryOptions = {}) =>
  createDummyDataFactory<${typeName}>(${schemaName}, options);

export const ${constantsName} = {
  collection: ${schemaName}.collection,
  domain: ${schemaName}.domain,
  idField: ${schemaName}.idField ?? "id",
  key: ${JSON.stringify(schema.key)},
} as const satisfies PrototypeSchemaRuntimeConstants;

export const ${cachedDummyName} = (
  tenantId: string,
  count = 1000,
  options: DummyDataFactoryOptions = {},
  cache: PrototypeRuntimeCache = prototypeRuntimeCache
): readonly ${typeName}[] =>
  cache.getDummyRecords(${schemaName}, { ...options, tenantId }, count, () =>
    ${factoryName}({ ...options, tenantId }).list(count)
  );

export const ${storeFactoryName} = (
  tenantId: string,
  initialRecords: readonly ${typeName}[] = [],
  cache: PrototypeRuntimeCache = prototypeRuntimeCache
): ${storeName} => {
  const scope = {
    collection: ${schemaName}.collection,
    domain: ${schemaName}.domain,
    tenantId,
  };
  const store = cache.getStore<${typeName}>(
    scope,
    () =>
      createTenantProjectionStore<${typeName}>(
        scope,
        (record) => String(record[${schemaName}.idField ?? "id"] ?? "")
      )
  );
  if (initialRecords.length > 0) {
    store.replace(initialRecords);
  }
  return store;
};

export const ${liveBindingName} = (
  options: Omit<LiveProjectionBindingOptions<${typeName}>, "scope" | "store"> & {
    tenantId: string;
    store?: ${storeName};
    cache?: PrototypeRuntimeCache;
  }
): LiveProjectionBinding<${typeName}> => {
  const { tenantId, store, cache = prototypeRuntimeCache, ...bindingOptions } = options;
  const resolvedStore = store ?? ${storeFactoryName}(tenantId, [], cache);
  return createLiveProjectionBinding<${typeName}>({
    ...bindingOptions,
    scope: {
      collection: ${schemaName}.collection,
      domain: ${schemaName}.domain,
      tenantId,
    },
    store: resolvedStore,
  });
};

export const ${registerName} = (
  tenantId: string,
  store: ${storeName} = ${storeFactoryName}(tenantId)
): ${storeName} => {
  prototypeStoreRegistry.register(${JSON.stringify(schema.key)}, store);
  return store;
};

export const ${hookName} = () => prototypeStoreRegistry.use(${JSON.stringify(schema.key)});

export const ${fixtureName} = {
  empty: (): ${typeName}[] => [],
  happyPath: (tenantId = "tenant-prototype"): readonly ${typeName}[] =>
    ${cachedDummyName}(tenantId, 8, { seed: ${JSON.stringify(`${schema.key}:happy`)} }),
  invalidMissingId: (): ${typeName}[] =>
    ${factoryName}({ seed: ${JSON.stringify(`${schema.key}:invalid`)} }).list(1, () => ({
      [${schemaName}.idField ?? "id"]: "",
    })),
  highVolume: (tenantId = "tenant-prototype", count = 1000): readonly ${typeName}[] =>
    ${cachedDummyName}(tenantId, count, { seed: ${JSON.stringify(`${schema.key}:high-volume`)} }),
};

export const ${stateName} = {
  empty: (tenantId = "tenant-prototype"): PrototypeFixtureState<${typeName}> => ({
    collection: ${schemaName}.collection,
    domain: ${schemaName}.domain,
    name: ${JSON.stringify(`${schema.key}.empty`)},
    records: ${fixtureName}.empty(),
    tenantId,
  }),
  happyPath: (tenantId = "tenant-prototype"): PrototypeFixtureState<${typeName}> => ({
    collection: ${schemaName}.collection,
    domain: ${schemaName}.domain,
    name: ${JSON.stringify(`${schema.key}.happyPath`)},
    records: ${fixtureName}.happyPath(tenantId),
    tenantId,
  }),
  invalidMissingId: (tenantId = "tenant-prototype"): PrototypeFixtureState<${typeName}> => ({
    collection: ${schemaName}.collection,
    domain: ${schemaName}.domain,
    name: ${JSON.stringify(`${schema.key}.invalidMissingId`)},
    records: ${fixtureName}.invalidMissingId(),
    tenantId,
  }),
  highVolume: (tenantId = "tenant-prototype", count = 1000): PrototypeFixtureState<${typeName}> => ({
    collection: ${schemaName}.collection,
    domain: ${schemaName}.domain,
    name: ${JSON.stringify(`${schema.key}.highVolume`)},
    records: ${fixtureName}.highVolume(tenantId, count),
    tenantId,
  }),
};

export const ${benchmarkName}: readonly PrototypeBenchmarkFixture[] = [
  {
    lane: "dummy",
    name: ${JSON.stringify(`${schema.key}.dummy.list.1000`)},
    records: 1000,
    run: () => ${cachedDummyName}("tenant-benchmark", 1000, { seed: ${JSON.stringify(`${schema.key}:bench-dummy`)} }).length,
  },
  {
    lane: "store",
    name: ${JSON.stringify(`${schema.key}.store.replace.1000`)},
    records: 1000,
    run: () => {
      const records = ${factoryName}({ seed: ${JSON.stringify(`${schema.key}:bench-store`)} }).list(1000);
      const store = ${storeFactoryName}("tenant-benchmark", records);
      return store.getSnapshot().records.length;
    },
  },
  {
    lane: "store",
    name: ${JSON.stringify(`${schema.key}.store.apply.1000`)},
    records: 1000,
    run: () => {
      const records = ${factoryName}({ seed: ${JSON.stringify(`${schema.key}:bench-apply`)} }).list(1000);
      const store = ${storeFactoryName}("tenant-benchmark");
      records.forEach((record, index) => {
        const recordId = String(record[${schemaName}.idField ?? "id"] ?? index);
        store.apply({
          collection: ${schemaName}.collection,
          domain: ${schemaName}.domain,
          operation: "upsert",
          record,
          recordId,
          tenantId: "tenant-benchmark",
          version: index,
        });
      });
      return store.getSnapshot().records.length;
    },
  },
  {
    lane: "store",
    name: ${JSON.stringify(`${schema.key}.store.reset.1000`)},
    records: 1000,
    run: () => {
      const records = ${factoryName}({ seed: ${JSON.stringify(`${schema.key}:bench-reset`)} }).list(1000);
      const store = ${storeFactoryName}("tenant-benchmark", records);
      store.reset();
      return store.getSnapshot().records.length;
    },
  },
  {
    lane: "store",
    name: ${JSON.stringify(`${schema.key}.store.selector.1000`)},
    records: 1000,
    run: () => {
      const records = ${factoryName}({ seed: ${JSON.stringify(`${schema.key}:bench-selector`)} }).list(1000);
      const store = ${storeFactoryName}("tenant-benchmark", records);
      const selectedId = String(records[500]?.[${schemaName}.idField ?? "id"] ?? "");
      return store.get(selectedId);
    },
  },
];
`;
}

function renderRegistry({ protoRootLabel, schemas }) {
  const schemaNames = schemas.map((schema) => `${lowerFirst(safePascalIdentifier(schema.messageName))}Schema`);
  const constantsNames = schemas.map((schema) => `${lowerFirst(safePascalIdentifier(schema.messageName))}RuntimeConstants`);
  const benchmarkNames = schemas.map((schema) => `${lowerFirst(safePascalIdentifier(schema.messageName))}BenchmarkFixtures`);
  const domainEntries = schemas
    .map((schema) => {
      const base = safePascalIdentifier(schema.messageName);
      const variableBase = lowerFirst(base);
      return `  {
    benchmarkFixtures: ${variableBase}BenchmarkFixtures,
    connectLiveProjection: connect${base}LiveProjection,
    constants: ${variableBase}RuntimeConstants,
    createDummyRecords: createCached${base}DummyRecords,
    createStore: create${base}Store,
    fixtureStates: ${variableBase}FixtureStates,
    registerStore: register${base}Store,
    schema: ${variableBase}Schema,
  },`;
    })
    .join("\n");
  const schemaEntries = schemas
    .map((schema) => `  ${JSON.stringify(schema.key)}: ${lowerFirst(safePascalIdentifier(schema.messageName))}Schema,`)
    .join("\n");

  return `export const prototypeSchemaSource = ${JSON.stringify(protoRootLabel)};

export const prototypeSchemas = [${schemaNames.join(", ")}] as const satisfies readonly DummySchemaSpec[];

export const prototypeSchemaRuntimeConstants = [${constantsNames.join(", ")}] as const satisfies readonly PrototypeSchemaRuntimeConstants[];

export const prototypeSchemaByCollection = {
${schemaEntries}
} as const;

export const prototypeBenchmarkFixtures = [
${benchmarkNames.map((name) => `  ...${name},`).join("\n")}
] as const satisfies readonly PrototypeBenchmarkFixture[];

export const prototypeDomains = [
${domainEntries}
] as const satisfies readonly PrototypeDomainRuntime[];

export const createPrototypeTenantStores = (
  tenantId: string,
  cache: PrototypeRuntimeCache = prototypeRuntimeCache,
  dummyRecordCount = 8
): readonly TenantProjectionStore<Record<string, unknown>>[] =>
  prototypeDomains.map((domain) => {
    const records =
      dummyRecordCount > 0
        ? domain.createDummyRecords(tenantId, dummyRecordCount, { seed: \`\${domain.constants.key}:scaffold\` }, cache)
        : [];
    return domain.registerStore(tenantId, domain.createStore(tenantId, records, cache));
  });
`;
}

function stableJson(value) {
  return JSON.stringify(sortObject(value), undefined, 2);
}

function sortObject(value) {
  if (Array.isArray(value)) {
    return value.map(sortObject);
  }
  if (!value || typeof value !== "object") {
    return value;
  }
  return Object.fromEntries(
    Object.entries(value)
      .filter(([, entryValue]) => entryValue !== undefined)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, entryValue]) => [key, sortObject(entryValue)])
  );
}

function stableProtoRootLabel(protoRootArg, protoRoot) {
  const normalized = protoRoot.split(path.sep).join("/");
  if (normalized.endsWith("/api/protos")) {
    return "api/protos";
  }
  if (!path.isAbsolute(protoRootArg)) {
    return protoRootArg.split(path.sep).join("/");
  }
  return (path.relative(process.cwd(), protoRoot) || ".").split(path.sep).join("/");
}

function stripEntitySuffix(value) {
  return value.replace(ENTITY_SUFFIX, "");
}

function toSnakeCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function pluralizeSnake(value) {
  const parts = value.split("_");
  const last = parts.pop() ?? value;
  parts.push(pluralize(last));
  return parts.join("_");
}

function pluralize(value) {
  if (value.endsWith("s")) return value;
  if (value.endsWith("y") && !/[aeiou]y$/.test(value)) return `${value.slice(0, -1)}ies`;
  if (/(ch|sh|x|z)$/.test(value)) return `${value}es`;
  return `${value}s`;
}

function safePascalIdentifier(value) {
  const words = value
    .split(/[^A-Za-z0-9]+/)
    .flatMap((word) => word.split(/(?=[A-Z])/))
    .filter(Boolean);
  const identifier = words.map((word) => `${word[0].toUpperCase()}${word.slice(1)}`).join("");
  const safe = identifier.replace(/[^A-Za-z0-9_$]/g, "") || "Prototype";
  return /^[A-Za-z_$]/.test(safe) ? safe : `Prototype${safe}`;
}

function lowerFirst(value) {
  return `${value[0].toLowerCase()}${value.slice(1)}`;
}

function relativeToCwd(file) {
  return path.relative(process.cwd(), file) || ".";
}

main();
