version: "2"

linters:
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errorlint
    - gosec
    - govet
    - noctx
    - revive
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
