// Code generated by runtime-sdk/scripts/generate_binding_contracts.mjs. DO NOT EDIT.

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RuntimeBindingRequest {
    pub schema_version: u32,
    pub registry_id: u64,
    pub binding_id: u64,
    pub binding_revision: u64,
    pub resource_id: u64,
    pub resource_generation: u64,
    pub input_type_id: u64,
    pub output_type_id: u64,
    pub output_capacity: u32,
    pub max_transfer_bytes: u64,
    pub timeout_millis: u32,
    pub max_input_copy_bytes: u64,
}

impl RuntimeBindingRequest {
    pub const BYTES: usize = 104;
    pub fn encode_to(&self, dst: &mut [u8]) -> Result<(), &'static str> {
        if dst.len() != Self::BYTES {
            return Err("invalid binding frame size");
        }
        dst.fill(0);
        dst[4..8].copy_from_slice(&12u32.to_le_bytes());
        dst[8..16].copy_from_slice(&47244640256u64.to_le_bytes());
        dst[16..20].copy_from_slice(&self.schema_version.to_le_bytes());
        dst[24..32].copy_from_slice(&self.registry_id.to_le_bytes());
        dst[32..40].copy_from_slice(&self.binding_id.to_le_bytes());
        dst[40..48].copy_from_slice(&self.binding_revision.to_le_bytes());
        dst[48..56].copy_from_slice(&self.resource_id.to_le_bytes());
        dst[56..64].copy_from_slice(&self.resource_generation.to_le_bytes());
        dst[64..72].copy_from_slice(&self.input_type_id.to_le_bytes());
        dst[72..80].copy_from_slice(&self.output_type_id.to_le_bytes());
        dst[20..24].copy_from_slice(&self.output_capacity.to_le_bytes());
        dst[80..88].copy_from_slice(&self.max_transfer_bytes.to_le_bytes());
        dst[88..92].copy_from_slice(&self.timeout_millis.to_le_bytes());
        dst[96..104].copy_from_slice(&self.max_input_copy_bytes.to_le_bytes());
        Ok(())
    }
    pub fn decode(src: &[u8]) -> Result<Self, &'static str> {
        if src.len() != Self::BYTES
            || src[..4] != [0; 4]
            || src[4..8] != 12u32.to_le_bytes()
            || src[8..16] != 47244640256u64.to_le_bytes()
        {
            return Err("invalid binding frame layout");
        }
        Ok(Self {
            schema_version: u32::from_le_bytes(
                src[16..20].try_into().map_err(|_| "invalid field")?,
            ),
            registry_id: u64::from_le_bytes(src[24..32].try_into().map_err(|_| "invalid field")?),
            binding_id: u64::from_le_bytes(src[32..40].try_into().map_err(|_| "invalid field")?),
            binding_revision: u64::from_le_bytes(
                src[40..48].try_into().map_err(|_| "invalid field")?,
            ),
            resource_id: u64::from_le_bytes(src[48..56].try_into().map_err(|_| "invalid field")?),
            resource_generation: u64::from_le_bytes(
                src[56..64].try_into().map_err(|_| "invalid field")?,
            ),
            input_type_id: u64::from_le_bytes(src[64..72].try_into().map_err(|_| "invalid field")?),
            output_type_id: u64::from_le_bytes(
                src[72..80].try_into().map_err(|_| "invalid field")?,
            ),
            output_capacity: u32::from_le_bytes(
                src[20..24].try_into().map_err(|_| "invalid field")?,
            ),
            max_transfer_bytes: u64::from_le_bytes(
                src[80..88].try_into().map_err(|_| "invalid field")?,
            ),
            timeout_millis: u32::from_le_bytes(
                src[88..92].try_into().map_err(|_| "invalid field")?,
            ),
            max_input_copy_bytes: u64::from_le_bytes(
                src[96..104].try_into().map_err(|_| "invalid field")?,
            ),
        })
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RuntimeBindingReceipt {
    pub schema_version: u32,
    pub binding_revision: u64,
    pub resource_generation: u64,
    pub output_type_id: u64,
    pub output_bytes: u32,
    pub transferred_bytes: u64,
    pub input_copied_bytes: u64,
    pub status: u32,
}

impl RuntimeBindingReceipt {
    pub const BYTES: usize = 72;
    pub fn encode_to(&self, dst: &mut [u8]) -> Result<(), &'static str> {
        if dst.len() != Self::BYTES {
            return Err("invalid binding frame size");
        }
        dst.fill(0);
        dst[4..8].copy_from_slice(&8u32.to_le_bytes());
        dst[8..16].copy_from_slice(&30064771072u64.to_le_bytes());
        dst[16..20].copy_from_slice(&self.schema_version.to_le_bytes());
        dst[24..32].copy_from_slice(&self.binding_revision.to_le_bytes());
        dst[32..40].copy_from_slice(&self.resource_generation.to_le_bytes());
        dst[40..48].copy_from_slice(&self.output_type_id.to_le_bytes());
        dst[20..24].copy_from_slice(&self.output_bytes.to_le_bytes());
        dst[48..56].copy_from_slice(&self.transferred_bytes.to_le_bytes());
        dst[56..64].copy_from_slice(&self.input_copied_bytes.to_le_bytes());
        dst[64..68].copy_from_slice(&self.status.to_le_bytes());
        Ok(())
    }
    pub fn decode(src: &[u8]) -> Result<Self, &'static str> {
        if src.len() != Self::BYTES
            || src[..4] != [0; 4]
            || src[4..8] != 8u32.to_le_bytes()
            || src[8..16] != 30064771072u64.to_le_bytes()
        {
            return Err("invalid binding frame layout");
        }
        Ok(Self {
            schema_version: u32::from_le_bytes(
                src[16..20].try_into().map_err(|_| "invalid field")?,
            ),
            binding_revision: u64::from_le_bytes(
                src[24..32].try_into().map_err(|_| "invalid field")?,
            ),
            resource_generation: u64::from_le_bytes(
                src[32..40].try_into().map_err(|_| "invalid field")?,
            ),
            output_type_id: u64::from_le_bytes(
                src[40..48].try_into().map_err(|_| "invalid field")?,
            ),
            output_bytes: u32::from_le_bytes(src[20..24].try_into().map_err(|_| "invalid field")?),
            transferred_bytes: u64::from_le_bytes(
                src[48..56].try_into().map_err(|_| "invalid field")?,
            ),
            input_copied_bytes: u64::from_le_bytes(
                src[56..64].try_into().map_err(|_| "invalid field")?,
            ),
            status: u32::from_le_bytes(src[64..68].try_into().map_err(|_| "invalid field")?),
        })
    }
}
