// Code generated by runtime-sdk/scripts/generate_binding_contracts.mjs. DO NOT EDIT.

package placement

import (
	"encoding/binary"
	"errors"
)

var errBindingFrame = errors.New("invalid binding Cap’n Proto scalar frame")

const RuntimeBindingRequestBytes = 104

type RuntimeBindingRequest struct {
	SchemaVersion      uint32
	RegistryID         uint64
	BindingID          uint64
	BindingRevision    uint64
	ResourceID         uint64
	ResourceGeneration uint64
	InputTypeID        uint64
	OutputTypeID       uint64
	OutputCapacity     uint32
	MaxTransferBytes   uint64
	TimeoutMillis      uint32
	MaxInputCopyBytes  uint64
}

func (v RuntimeBindingRequest) EncodeTo(dst []byte) error {
	if len(dst) != RuntimeBindingRequestBytes {
		return errBindingFrame
	}
	clear(dst)
	binary.LittleEndian.PutUint32(dst[4:8], 12)
	binary.LittleEndian.PutUint64(dst[8:16], uint64(11)<<32)
	binary.LittleEndian.PutUint32(dst[16:], v.SchemaVersion)
	binary.LittleEndian.PutUint64(dst[24:], v.RegistryID)
	binary.LittleEndian.PutUint64(dst[32:], v.BindingID)
	binary.LittleEndian.PutUint64(dst[40:], v.BindingRevision)
	binary.LittleEndian.PutUint64(dst[48:], v.ResourceID)
	binary.LittleEndian.PutUint64(dst[56:], v.ResourceGeneration)
	binary.LittleEndian.PutUint64(dst[64:], v.InputTypeID)
	binary.LittleEndian.PutUint64(dst[72:], v.OutputTypeID)
	binary.LittleEndian.PutUint32(dst[20:], v.OutputCapacity)
	binary.LittleEndian.PutUint64(dst[80:], v.MaxTransferBytes)
	binary.LittleEndian.PutUint32(dst[88:], v.TimeoutMillis)
	binary.LittleEndian.PutUint64(dst[96:], v.MaxInputCopyBytes)
	return nil
}

func DecodeRuntimeBindingRequest(src []byte) (RuntimeBindingRequest, error) {
	var v RuntimeBindingRequest
	if len(src) != RuntimeBindingRequestBytes || binary.LittleEndian.Uint32(src[:4]) != 0 ||
		binary.LittleEndian.Uint32(src[4:8]) != 12 || binary.LittleEndian.Uint64(src[8:16]) != uint64(11)<<32 {
		return v, errBindingFrame
	}
	v.SchemaVersion = binary.LittleEndian.Uint32(src[16:])
	v.RegistryID = binary.LittleEndian.Uint64(src[24:])
	v.BindingID = binary.LittleEndian.Uint64(src[32:])
	v.BindingRevision = binary.LittleEndian.Uint64(src[40:])
	v.ResourceID = binary.LittleEndian.Uint64(src[48:])
	v.ResourceGeneration = binary.LittleEndian.Uint64(src[56:])
	v.InputTypeID = binary.LittleEndian.Uint64(src[64:])
	v.OutputTypeID = binary.LittleEndian.Uint64(src[72:])
	v.OutputCapacity = binary.LittleEndian.Uint32(src[20:])
	v.MaxTransferBytes = binary.LittleEndian.Uint64(src[80:])
	v.TimeoutMillis = binary.LittleEndian.Uint32(src[88:])
	v.MaxInputCopyBytes = binary.LittleEndian.Uint64(src[96:])
	return v, nil
}

const RuntimeBindingReceiptBytes = 72

type RuntimeBindingReceipt struct {
	SchemaVersion      uint32
	BindingRevision    uint64
	ResourceGeneration uint64
	OutputTypeID       uint64
	OutputBytes        uint32
	TransferredBytes   uint64
	InputCopiedBytes   uint64
	Status             uint32
}

func (v RuntimeBindingReceipt) EncodeTo(dst []byte) error {
	if len(dst) != RuntimeBindingReceiptBytes {
		return errBindingFrame
	}
	clear(dst)
	binary.LittleEndian.PutUint32(dst[4:8], 8)
	binary.LittleEndian.PutUint64(dst[8:16], uint64(7)<<32)
	binary.LittleEndian.PutUint32(dst[16:], v.SchemaVersion)
	binary.LittleEndian.PutUint64(dst[24:], v.BindingRevision)
	binary.LittleEndian.PutUint64(dst[32:], v.ResourceGeneration)
	binary.LittleEndian.PutUint64(dst[40:], v.OutputTypeID)
	binary.LittleEndian.PutUint32(dst[20:], v.OutputBytes)
	binary.LittleEndian.PutUint64(dst[48:], v.TransferredBytes)
	binary.LittleEndian.PutUint64(dst[56:], v.InputCopiedBytes)
	binary.LittleEndian.PutUint32(dst[64:], v.Status)
	return nil
}

func DecodeRuntimeBindingReceipt(src []byte) (RuntimeBindingReceipt, error) {
	var v RuntimeBindingReceipt
	if len(src) != RuntimeBindingReceiptBytes || binary.LittleEndian.Uint32(src[:4]) != 0 ||
		binary.LittleEndian.Uint32(src[4:8]) != 8 || binary.LittleEndian.Uint64(src[8:16]) != uint64(7)<<32 {
		return v, errBindingFrame
	}
	v.SchemaVersion = binary.LittleEndian.Uint32(src[16:])
	v.BindingRevision = binary.LittleEndian.Uint64(src[24:])
	v.ResourceGeneration = binary.LittleEndian.Uint64(src[32:])
	v.OutputTypeID = binary.LittleEndian.Uint64(src[40:])
	v.OutputBytes = binary.LittleEndian.Uint32(src[20:])
	v.TransferredBytes = binary.LittleEndian.Uint64(src[48:])
	v.InputCopiedBytes = binary.LittleEndian.Uint64(src[56:])
	v.Status = binary.LittleEndian.Uint32(src[64:])
	return v, nil
}
